### ISSUE TITLE
$data_dir should be documented in ReadMe

### ISSUE THREAD

**Issue by emoon3** [voxpupuli/puppet-confluence#129]
When trying to install Confluence 6.1.1, I kept getting "spring application context has not been set" errors when starting confluence.

It turns out that the $data_dir variable is set to undef unless you set it with a variable. As the module stands now, it seems like this MUST be set in order for it to work.

But there is no mention of it in the documentation.

**Comment by Tokynet** [comment]
I believe what you are seeing is the error caused by the typo mentioned [here](https://github.com/voxpupuli/puppet-confluence/pull/128)

For me, if I apply the basic class w/o defining anything else, the $data_dir does get populated (but i'm pulling master branch of this repo instead of the tag, since the fix is yet to make it to a tag release)

**Comment by emoon3** [comment]
Ahh, ok. Thanks.

**Comment by juniorsysadmin** [comment]
Fixed by #128
